entrepreneurs/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('',include('home.urls')),
    path('accounts/',include('accounts.urls')),
    path('admin/', admin.site.urls)
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('',views.home, name = 'home'),
	path('profile',views.profile, name = 'profile'),
	path('search',views.search, name = 'search')
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class entrepreneur(models.Model):
	user = models.OneToOneField(User, on_delete = models.CASCADE)
	photo = models.ImageField(upload_to='photos', blank=True)
	intro = models.CharField(max_length=300, blank=True)
	industry = models.CharField(max_length = 50, blank=True)
	city = models.CharField(max_length=100, blank=True)
	state = models.CharField(max_length=100, blank=True)
	country = models.CharField(max_length=100, blank=True)
	about = models.TextField(blank=True)
	linkedin_url = models.URLField(max_length=200, blank=True)
	facebook_url = models.URLField(max_length=200, blank=True)
	instagram_url = models.URLField(max_length=200, blank=True)
	business_pic1 = models.ImageField(upload_to='bpics', blank=True)
	business_pic2 = models.ImageField(upload_to='bpics', blank=True)
	business_pic3 = models.ImageField(upload_to='bpics', blank=True)
	business_pic4 = models.ImageField(upload_to='bpics', blank=True)
	business_pic5 = models.ImageField(upload_to='bpics', blank=True)

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from accounts.models import entrepreneur
from django.contrib.auth.models import User
# Create your views here.
def home(request):
	ents = entrepreneur.objects.all()
	#print(ents)
	return render(request,'home.html',{'ents':ents})

def profile(request):
	if 'id' in request.GET:
		username = request.GET['id']
		user = User.objects.get(username=username)
		if request.user == user:
			is_owner = True
		else:
			is_owner = False
	else:
		user = request.user
		is_owner = True
	print(user)
	ent = user.entrepreneur
	desc_paras = ent.about.split('\n')
	num_pics = 5
	pic_urls = []
	try:
		pic_urls.append(ent.business_pic1.url)
	except:
		num_pics-=1
	try:
		pic_urls.append(ent.business_pic2.url)
	except:
		num_pics-=1
	try:
		pic_urls.append(ent.business_pic3.url)
	except:
		num_pics-=1
	try:
		pic_urls.append(ent.business_pic4.url)
	except:
		num_pics-=1
	try:
		pic_urls.append(ent.business_pic5.url)
	except:
		num_pics-=1
	return render(request,'view_profile.html',{'ent':ent, 'desc_paras': desc_paras,'is_owner':is_owner, 'pic_urls':pic_urls})
	
def search(request):
	if request.method == 'POST':
		keyword = request.POST['keyword']
		keywords = keyword.split(' ')
		results = []
		for kw in keywords:
			first_name_key = (User.objects.filter(first_name__iexact=kw))
			for fnk in first_name_key:
				results.append(fnk.entrepreneur)
			last_name_key = (User.objects.filter(last_name__iexact=kw))
			for lnk in last_name_key:
				results.append(lnk.entrepreneur)
			results.extend(entrepreneur.objects.filter(intro__icontains=kw))
			results.extend(entrepreneur.objects.filter(industry__icontains=kw))
			results.extend(entrepreneur.objects.filter(city__icontains=kw))
			results.extend(entrepreneur.objects.filter(state__icontains=kw))
			results.extend(entrepreneur.objects.filter(country__icontains=kw))
		results = list(dict.fromkeys(results))
		user = User.objects.get(username="sivgos")
		ent = user.entrepreneur
		return render(request,"search.html", {"result_available": len(results), "results": results})
	else:
		return render(request,"search.html",{"result_available": -1, "results": []})

templates/edit_profile.html
{% load static %}
<html>
<head>
  <link rel="stylesheet" href="{% static 'css/styles_register.css' %}">
</head>
<body bgcolor = "lightgreen">
{% block content %}
 <form action="edit_profile" method='post' style="border:1px solid #ccc" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="container">
    <h1>Welcome {{user.first_name}} {{user.last_name}}</h1>
    <p>Please fill in this form to create your profile.</p>
    <hr>
    {% if ent_exist %}
    <label for="intro"><b>Enter a brief into about yourself</b></label>
    <input type="text" value="{{user.entrepreneur.intro}}" autocomplete="off" name="intro" required>

    <label for="industry"><b>Which industry best describes your work? </b></label>
    <input type="text" value="{{user.entrepreneur.industry}}" autocomplete="off" name="industry" required>

    <label for="city"><b>Enter the name of your town or city: </b></label>
    <input type="text" value="{{user.entrepreneur.city}}" autocomplete="off" name="city" required>

    <label for="state"><b>Enter the name of your state: </b></label>
    <input type="text" value="{{user.entrepreneur.state}}" autocomplete="off" name="state" required>

    <label for="country"><b>Enter the name of your country: </b></label>
    <input type="text" value="{{user.entrepreneur.country}}" autocomplete="off" name="country" required>
    
     <label for="about"><b>Write your detailed bio</b></label>
     <textarea rows = "20" cols = "100" name = "about"> {{user.entrepreneur.about}} </textarea> <br><br><br>

     <label for="id_photo"> <b> Upload a New Profile Photo </b> </label> <br>
     {% if user.entrepreneur.photo.url is not None %}
     <img src="{{user.entrepreneur.photo.url}}" width="300" height="300" alt=""> <br><br>
     {% endif %}
     <input type="file" name="photo" id="id_photo" accept="image/*"> <br><br><br>

     <label for="external_urls"> <b> Enter any links to your website or social media profiles:</b> </label> <br>
     <p>Linkedin Profile: </p>
     <input type="url" value = {{user.entrepreneur.linkedin_url}} name = "linkedin_url"> <br>
     <p>Facebook Profile: </p>
     <input type="url" value = {{user.entrepreneur.facebook_url}} name = "facebook_url"> <br>
     <p>Instagram Profile: </p>
     <input type="url" value = {{user.entrepreneur.instagram_url}} name = "instagram_url"> <br><br><br>

     <label for="business_pics"><b> Upload maximum five memorable photos of your business </b> </label> <br>

 
    {% if user.entrepreneur.business_pic1.url is not None %}
     <img src="{{user.entrepreneur.business_pic1.url}}" width="350" height="350" alt="">
     <input type="checkbox" id="del_business_pic1" name="del_business_pic1" value="Delete this image"> Delete this image <br><br>
     {% else %}
     <input type="file" name="business_pic1" id="id_business_pic1" accept="image/*"> <br>
     {% endif %}

     {% if user.entrepreneur.business_pic2.url is not None %}
     <img src="{{user.entrepreneur.business_pic2.url}}" width="350" height="350" alt="">
     <input type="checkbox" id="del_business_pic2" name="del_business_pic2" value="Delete this image"> Delete this image<br><br>
     {% else %}
     <input type="file" name="business_pic2" id="id_business_pic2" accept="image/*"> <br>
     {% endif %}

     {% if user.entrepreneur.business_pic3.url is not None %}
     <img src="{{user.entrepreneur.business_pic3.url}}" width="350" height="350" alt="">
     <input type="checkbox" id="del_business_pic3" name="del_business_pic3" value="Delete this image"> Delete this image<br><br>
     {% else %}
     <input type="file" name="business_pic3" id="id_business_pic3" accept="image/*"> <br>
     {% endif %}

     {% if user.entrepreneur.business_pic4.url is not None %}
     <img src="{{user.entrepreneur.business_pic4.url}}" width="350" height="350" alt="">
     <input type="checkbox" id="del_business_pic4" name="del_business_pic4" value="Delete this image"> Delete this image <br><br>
     {% else %}
     <input type="file" name="business_pic4" id="id_business_pic4" accept="image/*"> <br>
     {% endif %}

     {% if user.entrepreneur.business_pic5.url is not None %}
     <img src="{{user.entrepreneur.business_pic5.url}}" width="350" height="350" alt="">
     <input type="checkbox" id="del_business_pic5" name="del_business_pic5" value="Delete this image"> Delete this image<br><br>
     {% else %}
     <input type="file" name="business_pic5" id="id_business_pic5" accept="image/*"> <br>
     {% endif %}

    {% else %}

    <label for="intro"><b>Enter a brief into about yourself</b></label>
    <input type="text" placeholder="Maximum 300 characters" name="intro" required>

    <label for="industry"><b>Which industry best describes your work? </b></label>
    <input type="text" placeholder="Example: Edutech, Digital Marketing, etc. " name="industry" required>

    <label for="city"><b>Enter the name of your town or city: </b></label>
    <input type="text" placeholder="Enter the name of your town or city" autocomplete="off" name="city" required>

    <label for="state"><b>Enter the name of your state: </b></label>
    <input type="text" placeholder="Enter the name of your town or state" autocomplete="off" name="state" required>

    <label for="country"><b>Enter the name of your country: </b></label>
    <input type="text" placeholder="Enter the name of your town or country" autocomplete="off" name="country" required>
    
     <label for="about"><b>Write your detailed bio</b></label>
     <textarea rows = "20" cols = "100" name = "about"> Write here </textarea>
    
     <label for="id_photo"> <b> Upload a Profile Photo </b> </label>
     <input type="file" name="photo" id="id_photo" accept="image/*"> <br><br>

     <label for="external_urls"> <b> Enter any links to your website or social media profiles:</b> </label> <br>
     <p>Linkedin Profile: </p>
     <input type="url" value = "http://www.linkedin.com" name = "linkedin_url"> <br>
     <p>Facebook Profile: </p>
     <input type="url" value = "http://www.facebook.com" name = "facebook_url"> <br>
     <p>Instagram Profile: </p>
     <input type="url" value = "http://www.instagram.com" name = "instagram_url"> <br><br><br>

     <label for="business_pics"><b> Upload maximum five memorable photos of your business </b> </label> <br>
     <input type="file" name="business_pic1" id="id_business_pic1" accept="image/*"> <br>
     <input type="file" name="business_pic2" id="id_business_pic2" accept="image/*"> <br>
     <input type="file" name="business_pic3" id="id_business_pic3" accept="image/*"> <br>
     <input type="file" name="business_pic4" id="id_business_pic4" accept="image/*"> <br>
     <input type="file" name="business_pic5" id="id_business_pic5" accept="image/*"> <br>
      {% endif %} 

    <div class="clearfix">
      <button type="button" onclick="location.href='{% url 'home' %}'" class="cancelbtn"> Cancel</button>
      <button type="submit" class="signupbtn">Update</button>
    </div>
  </div>
</form> 
 {% endblock %}
</html>

templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title> Entrepreneurs' Connect </title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="#">Entrepreneurs' Connect</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">About</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="/accounts/view_profile">Hi {{user.first_name}} !!</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/accounts/logout">Logout</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="/accounts/register">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/accounts/login">Login</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  <!-- Header -->
  <header class="bg-primary py-5 mb-5">
    <div class="container h-100">
      <div class="row h-100 align-items-center">
        <div class="col-lg-12">
          <h1 class="display-4 text-white mt-5 mb-2">Entrepreneurs' Connect</h1>
          <p class="lead mb-5 text-white-50">Entrepreneurs' Connect is a social media platform that connects the emerging Entrepreneurs' throught Assam </p>
        </div>
      </div>
    </div>
  </header>

  <!-- Page Content -->
  <div class="container">

    <div class="row">
      <div class="col-md-8 mb-5">
        <h2>What We Do</h2>
        <hr>
        <p>Browse through all the emerging entrepreneurs' profiles in the following links and get the information about their entrprise.</p>
        <p>If you are an emerging entrepreneur, you may consider signining up and creating your profile with us. Alternatively, you may contact us and we will help you in featuring your profile in our site.</p>

        <a class="btn btn-primary btn-lg" href="/search">Search</a>

      </div>
      <div class="col-md-4 mb-5">
        <h2>Contact Us</h2>
        <hr>
        <address>
          <strong>Entrepreneur's Connecr</strong>
          <br>Guwahati
          <br>Assam, India
          <br>
        </address>
        <address>
          <abbr title="Phone">P:</abbr>
          (123) 456-7890
          <br>
          <abbr title="Email">E:</abbr>
          <a href="mailto:#">contact@example.com</a>
        </address>
      </div>
    </div>
    <!-- /.row -->

    <div class="row">
      {% for ent in ents %}
      <div class="col-md-4 mb-5">
        <div class="card h-100">
          <img class="card-img-top" src="{{ent.photo.url}}" width="300" height="300" alt="">
          <div class="card-body">
            <h4 class="card-title">{{ent.user.first_name}} {{ent.user.last_name}}</h4>
            <p class="card-text">{{ent.intro}}</p>
          </div>
          <div class="card-footer">
            <a href="/profile?id={{ent.user.username}}" class="btn btn-primary">Visit Profile</a>
          </div>
        </div>
      </div>

      {% endfor %}
    </div>

    <!-- /.row -->

  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Entrepreneurs' Connect 2020</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

</body>

</html>

templates/login.html
{% load static %}
<html>
<head>
  <link rel="stylesheet" href="{% static 'css/styles_register.css' %}">
</head>
<body bgcolor = "lightgreen">
{% block content %}
 <form action="login" method='post' style="border:1px solid #ccc">
  {% csrf_token %}
  <div class="container">
    <h1>Log In</h1>
    <p>Please enter your credentials to login.</p>
    {% for message in messages %}
	<h3> <span class="redText"> {{message}} </span></h3>
    {% endfor %}
    <p> New User? <a href="/accounts/register"> Register </a> <p>
    <hr>
    {% if message != 'no_msg' %}
	<h3> <span class="redText"> {{message}} </span></h3>
    {% endif %}
    <label for="username"><b>UserName</b></label>
    <input type="text" placeholder="Enter User Name or Email Id" name="username" required>

    <label for="psw"><b>Password</b></label>
    <input type="password" placeholder="Enter Password" name="password" required>
    <div class="clearfix">
      <button type="button" onclick="location.href='{% url 'home' %}'" class="cancelbtn"> Cancel</button>
      <button type="submit" class="signupbtn">Sign In</button>
    </div>
  </div>
</form> 
 {% endblock %}
</html>

templates/register.html
{% load static %}
<html>
<head>
  <link rel="stylesheet" href="{% static 'css/styles_register.css' %}">
</head>
<body bgcolor = "lightgreen">
{% block content %}
 <form action="register" method='post' style="border:1px solid #ccc">
  {% csrf_token %}
  <div class="container">
    <h1>Sign Up</h1>
    <p>Please fill in this form to create an account.</p>
    <p> Already have an account? <a href="/accounts/login"> Login </a> <p>
    <hr>
    {% for message in messages %}
	<h3> <span class="redText"> {{message}} </span></h3>
    {% endfor %}

    {% if data is None %}
    <label for="first_name"><b> First Name</b></label>
    <input type="text" placeholder="Enter your first name" name="first_name" required>

    <label for="last_name"><b> Last Name</b></label>
    <input type="text" placeholder="Enter your last name" name="last_name" required>

    <label for="email"><b> Email</b></label>
    <input type="email" placeholder="Enter Email" name="email" required>

    <label for="username"><b> Username</b></label>
    <input type="text" placeholder="You may use your email id as Username" name="username" required>

    {% else %}

    <label for="first_name"><b> First Name</b></label>
    <input type="text" value={{first_name}} name="first_name" required>

    <label for="last_name"><b> Last Name</b></label>
    <input type="text" value={{last_name}} name="last_name" required>

    <label for="email"><b> Email</b></label>
    <input type="email" value={{email}} name="email" required>

    <label for="username"><b> Username</b></label>
    <input type="text" value={{username}} name="username" required>
    {% endif %}

    <label for="password1"><b> Password</b></label>
    <input type="password" placeholder="Enter Password" name="password1" required>

    <label for="password2"><b> Repeat Password</b></label>
    <input type="password" placeholder="Repeat Password" name="password2" required>

    <p>By creating an account you agree to our <a href="#" style="color:dodgerblue">Terms & Privacy</a>.</p>

    <div class="clearfix">
      <button type="button" onclick="location.href='{% url 'home' %}'" class="cancelbtn"> Cancel</button>
      <button type="submit" class="signupbtn">Sign Up</button>
    </div>
  </div>
</form> 
 {% endblock %}
</html>

templates/search.html
{% load static %}
<html>
<head>
  <link rel="stylesheet" href="{% static 'css/styles_register.css' %}">
</head>
<body bgcolor = "lightgreen">
{% block content %}
 <form action="search" method='post' style="border:1px solid #ccc">
  {% csrf_token %}
  <div class="container">
    <h1>Search Entrepreneurs</h1>
    <p>Please enter your keywords to search.</p>
    <label for="keyword"><b>Search Terms</b></label>
    <input type="text" placeholder="Keyword or Keyphrase" name="keyword" required>
    <div class="clearfix">
      <button type="button" onclick="location.href='{% url 'home' %}'" class="cancelbtn"> Cancel</button>
      <button type="submit" class="signupbtn">Search</button>
    </div>
   {% if result_available == 0 %}
   	<h3> No Search Results Found </h3>
   {% elif result_available > 0 %}
       <h3> Search Results </h3>
   {% for ent in results %}
   <div class="result">
     Name:  <a href = "/profile?id={{ent.user.username}}">{{ent.user.first_name}} {{ent.user.last_name}}</a><br>
     Industry: {{ent.industry}}<br>
     About: {{ent.intro}}<br>
     Location: {{ent.city}}, {{ent.state}}, {{ent.country}}<br>
   </div> 
   <br><br>
  {% endfor %}
  {% endif %}

  </div>
</form> 

 {% endblock %}
</html>

templates/test.html
<html>
<p>{{ent.intro}}</p>
<p>{{ent.industry}}</p>
<p>{{ent.city}}</p>
<p>{{ent.state}}</p>
<p>{{ent.country}}</p>
<pre>{{ent.about}}</pre>
</html>

templates/view_profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title> Entrepreneurs' Connect </title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="#">Entrepreneurs' Connect</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">About</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="/accounts/view_profile">Hi {{user.first_name}} !!</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/accounts/logout">Logout</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="/accounts/register">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/accounts/login">Login</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  <-- Header -->
  <header class="bg-primary py-5 mb-5">
    <div class="container h-100">
      <div class="row h-100 align-items-center">
        <div class="col-lg-12">
          <h1 class="display-4 text-white mt-5 mb-2">{{ent.user.first_name}} {{ent.user.last_name}}</h1>
          <p class="lead mb-5 text-white-50">{{ent.intro}} </p>
        </div>
      </div>
    </div>
  </header>

  <!-- Page Content -->
  <div class="container">
    <div class="row">
      <div class="col-md-8 mb-5">
        <h2>About {{ent.user.first_name}} {{ent.user.last_name}}</h2>
        <hr>
	{% for para in desc_paras %}
        <p> {{para}} </p>
	{% endfor %}
	{% if is_owner %}
        <a class="btn btn-primary btn-lg" href="/accounts/edit_profile">Edit Profile &raquo;</a>
        {% endif %}
      </div>
      <div class="col-md-4 mb-5">
        <img class="card-img-top" src="{{ent.photo.url}}" width="300" height="300" alt="">
        <hr>
        <address>
          <strong>{{ent.city}}, {{ent.state}}</strong>
          <br>{{ent.country}}
          <br>
          <br>
        </address>
        <address>
          <a href = {{ent.linkedin_url}}> <img src = "{%static 'images/linkedin.png' %}" width="50" height="50"> </a>
          <a href = {{ent.facebook_url}}> <img src = "{%static 'images/facebook.png' %}" width="50" height="50"> </a>
          <a href = {{ent.instagram_url}}> <img src = "{%static 'images/instagram.png' %}" width="50" height="50"> </a>
        </address>
      </div>
    </div>
    
 <!-- Slideshow container -->
<div class="Photos">
<center>
  <!-- Full-width images with number and caption text -->
  {% for pic_url in pic_urls %}
    <img src={{pic_url}} height="300"></img><br>
  {% endfor %}
</center>
 </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Entrepreneurs' Connect 2020</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

</body>

</html>